export const activities = [
  // 🔥 Productive But Fun Activities  
  "Learn five useful phrases in a new language (like ordering coffee ☕)",
  "Write a letter or a heartfelt email to a friend you haven’t spoken to in a while ✉️",
  "Organize one messy drawer or shelf in your home 🏠",
  "Start a mini gratitude journal—write down 3 things you appreciate today ✍️",
  "Learn how to fold a piece of paper into a cool origami shape (like a crane 🦢)",
  "Review your monthly expenses and find one small way to save money 💰",
  "Do a 5-minute guided meditation to reset your focus 🧘‍♀️",
  "Research a random historical event that sounds interesting 📖",
  "Write down five small goals for the next week 📆",
  "Delete 10 old or unnecessary photos from your phone 📸",
  "Write a micro-story (exactly 50 words) or a short poem 📝",
  "Update your resume or portfolio with a new achievement 💼",
  "Try a new note-taking or productivity app for fun 📱",
  "Watch a TED Talk or a YouTube tutorial on something new 🎥",
  "Make a ‘someday’ list of things you want to do in the future 🏔️",
  "Learn a simple, impressive magic trick 🎩",
  "Sketch a rough wireframe or concept for a random app idea 📱",
  "Take a fun personality or career quiz 🔍",
  "Organize your bookmarks or saved articles online 🗂️",
  "Try a brain-training game like Sudoku or a logic puzzle 🧠",
  
  // 🎉 Fun and Creative Activities  
  "Have a mini indoor picnic with snacks and a fun playlist 🍎",
  "Build a cozy pillow fort and read or watch something inside 🏰",
  "Learn a simple dance move or follow a fun dance tutorial 🕺",
  "Draw yourself as a superhero and come up with a cool power ✍️",
  "Make paper airplanes and see which design flies the farthest ✈️",
  "Create a scavenger hunt list and try to find all the items in your house 🔎",
  "Have a mini karaoke session with your favorite song 🎤",
  "Invent a new simple card game using a deck of playing cards ♠️",
  "Line up random objects and create a small domino effect 🏗️",
  "Try sketching or doodling something without lifting your pen ✏️",
  "Write a funny haiku about something random (like your socks 🧦)",
  "Create a funny short story using random emojis as prompts 😂",
  "Experiment with a photo editing app and create something cool 📸",
  "Try writing a limerick or a rhyming poem 🎶",
  "Create a new playlist with songs that match a specific mood 🎵",
  "Recreate a simple dish or snack from a cooking video 🍳",
  "Try drawing a famous painting in your own style 🎨",
  "Record yourself reading a short story or poem with dramatic flair 🎭",
  "Make a simple stop-motion animation using objects on your desk 📽️",
  
  // 🛁 Relaxing but Engaging Activities  
  "Do a quick stretching routine to loosen up your muscles 🏃‍♀️",
  "Make a fancy cup of coffee or tea and enjoy it mindfully ☕",
  "Put on an old favorite album and listen to it without distractions 🎧",
  "Take a slow, mindful walk outside and notice small details 🌳",
  "Write down five things that made you smile today 😊",
  "Watch a calming ASMR or nature video to unwind 🌊",
  "Create a vision board (digital or paper) for your next big goal 📌",
  "Look up design inspiration on Pinterest or Dribbble 🎨",
  "Rewatch an episode of a comfort show or a funny YouTube video 📺",
  "Give yourself a quick DIY spa session (face mask, hand massage, etc.) 💆‍♀️"

  // 🎨 Productive Activities for a Product Designer  
  "Analyze a top-tier product and break down its UX/UI 🧐",
  "Redesign a small feature from an app you use often ✍️",
  "Do a 30-minute design challenge to solve a random problem ⏳",
  "Browse award-winning designs on Awwwards, Behance, or Dribbble 🎨",
  "Rewrite a past project case study to improve storytelling 📖",
  "Create a micro-interaction animation using Figma or Framer 🎬",
  "Sketch UI ideas on paper to focus on layout and structure 📝",
  "Declutter your design files and name layers properly 📂",
  "Try designing a UI without using any colors for better contrast understanding 🎭",
  "Recreate a well-known app interface purely from memory 🧠",

  // 📖 Activities for an Avid Reader  
  "Read one chapter from a pending book on your to-read list 📚",
  "Summarize a book you recently read in a few sentences 📝",
  "Listen to an audiobook while doing another task 🎧",
  "Write a book review and post it online 📖",
  "Read a design-related article and take notes 📰",
  "Discover a new book genre and pick one to explore 📚",
  "Revisit a childhood favorite book for nostalgia 🌟",
  "Join a book club or online reading community 📌",
  "Create a reading tracker to keep yourself accountable ✅",
  "Write down 3 key lessons from your latest read 🏆",

  // 🖊️ Journaling & Self-Reflection Activities  
  "Write a journal entry about your day or a recent experience 📔",
  "List 3 things you're grateful for today 💡",
  "Write a letter to your future self ✉️",
  "Describe your ideal day in vivid detail 🎭",
  "Write a short story or a poem based on a random prompt 🖊️",
  "Brainstorm 10 new ideas for a creative project 💡",
  "Reflect on a recent challenge and what you learned from it 🤔",
  "Create a 'lessons learned' journal for mistakes and growth 📓",
  "Write about a moment that made you smile recently 😊",
  "Doodle in your journal instead of writing—visual journaling can be fun! 🎨",

  // 🗣️ Communication & Public Speaking Activities  
  "Practice explaining a complex topic in a simple way 🗣️",
  "Record yourself speaking and analyze your tone and clarity 🎙️",
  "Write a LinkedIn post about something you recently learned ✍️",
  "Have a deep conversation with a friend about an interesting topic ☕",
  "Join a discussion forum and contribute to a thoughtful thread 💬",
  "Watch a TED Talk and summarize the key takeaways 📺",
  "Read a public speaking tip and practice it in daily conversations 🎤",
  "Write a persuasive argument for a random topic to improve structuring skills ⚖️",
  "Rehearse a 30-second introduction about yourself in an engaging way 👋",
  "Analyze a great speech or talk and break down what makes it powerful 🎭",

  // 💪 Fitness & Well-being Activities  
  "Do a 5-minute stretching session to reset your body 🧘‍♀️",
  "Take a quick walk outside and notice the small details in nature 🌿",
  "Try a short home workout or yoga flow for energy ⚡",
  "Drink a full glass of water and hydrate properly 💧",
  "Do 20 squats, push-ups, or jumping jacks to stay active 🏋️‍♀️",
  "Try a guided breathing exercise for relaxation 🌬️",
  "Dance to a favorite song for an instant mood boost 💃",
  "Try a new healthy snack or smoothie recipe 🥑",
  "Go up and down the stairs a few times as a quick cardio burst 🏃‍♀️",
  "Take a posture check and adjust your sitting position 🏞️",

  // 🚀 Learning New & Upcoming Tech  
  "Read an article about an emerging tech trend (like AI, Web3, or AR) 🚀",
  "Watch a tutorial on a new design tool or software 🖥️",
  "Try out a no-code tool and build something simple ⚙️",
  "Follow a tech influencer or designer on social media for insights 👀",
  "Write down 3 tech concepts you want to learn more about 📌",
  "Experiment with a new coding language or framework 🏗️",
  "Read a case study about how tech is transforming industries 🔬",
  "Learn about a recent breakthrough in AI or machine learning 🤖",
  "Take a short online course or lesson on an unfamiliar tech topic 🎓",
  "Explore an open-source project and see how it works 🔍"
  
];
